### ISSUE TITLE
gMicroMC/phy_stage/compile_cuMC, the compile command needs a change

### ISSUE THREAD

**Issue by Piponater** [utaresearch/gMicroMC#1]
From:
/usr/local/cuda-10.1/bin/nvcc microMC.cu readtbl.cu -G -g -arch=sm_35 -rdc=true -lcudadevrt -lcuda -lcudart -o microMC
 
To:
nvcc microMC.cu readtbl.cu -G -g -arch=sm_35 -rdc=true -lcudadevrt -lcuda -lcudart -o microMC
 
since most users will have nvcc in there PATH already just nvcc is better, a lot of users will end up having to edit this if they don’t have this exact path and encounter errors on their system whilst compiling.

Thank you

**Comment by laiyf94** [comment]
Thanks for the comment. Typically, nvcc is already in the PATH parameter. Hence, the file was changed accordingly.
