### ISSUE TITLE
prechem_stage/main.cu (Line 40)

### ISSUE THREAD

**Issue by Piponater** [utaresearch/gMicroMC#2]
prechem_stage/main.cu (Line 40):

parData_pc.readInitialParticles_GEANT4("../phy_stage/output/result.txt");
 
This directory doesn’t exist in the file structure of the code, so an empty directory: ./phy_stage/output is needed to be made.

Without it present, segfaults are received when running the code due to it not existing.

**Comment by laiyf94** [comment]
Thanks for the comment. Empty folder is omitted in the uploading process. To make sure the folder ./phy_stage/output existing, change (one line in main function to check existence of the folder) was made in the scipts in physics stage. 
However, the parameter here was an old version (read results from txt file), which is actually useless in current version (read results from binary file). Changes can be tracked in the definition of readInitialParticles_GEANT4 in initialization.cu. Thus, the fuction was modified to remove the parameter in the updated files.
