### ISSUE TITLE
How to Run section updating

### ISSUE THREAD

**Issue by Piponater** [utaresearch/gMicroMC#3]
Doing the steps to run the code manually doesn’t work/are a bit confusing (following the instructions in the readme in the how to run section):
 
./phy_stage/microMC config.txt
./prechem_stage/prechem 0
….
 
Since the code is hard wired to read paths relative to the current directory from where the executable is run, these need to be executed in the directory they are located in ( just like gMicroMC-master/main.c does ), not using the paths above.
 
It would be good if the  How to Run section could be changed a little bit to reflect this.  Also in part III the instructions  “cp ./phy_stage/output/outputtotalphy.dat ./chem_stage/Results” doesn’t work since outputtotalphy.dat doesn’t exist and isn’t produced by  running “./prechem 0”, it should be “cp ./phy_stage/output/totalphy.dat ./chem_stage/Results”

**Comment by laiyf94** [comment]
Thanks for the comments. Path has been specified for each sub-program. The typos were corrected.
