### ISSUE TITLE
Binary output.dat reading

### ISSUE THREAD

**Issue by chiadl** [utaresearch/gMicroMC#7]
Hi again,
I was wondering if you might share how do you read the binary files and combine their information after the simulation.
Since they are binary file.dat I am not able to read and process them.

Moreover, I am trying to use this code along with Geant4, what lower energy cut is used for the produced electrons in gMicro?

Many thanks!

**Comment by laiyf94** [comment]
For your first question, we are sorry that there is not enough explanation on the output. We are trying to make new version and add more comments. Please wait for the new version. Or you can explore the output function of each module on your own. It is not difficult to how the binary files are organized.

The lowest energy cut for electron transport is 5 eV.

**Comment by chiadl** [comment]
Thank you for your answer and explanation. I will wait for the new version.
But regardless of the data inside of the file, how do you read it once the simulation has written it?
I am trying with MatLab but it gives me some problems since the file is binary and not ASCII.

Many thanks

**Comment by YujieChi** [comment]
Hi there,

If you check the data written format inside the code, you should be able to read it through Matlab with the same format. It is a relatively straightforward process. Or you could post your specific reading problem.
Thanks.

**Comment by chiadl** [comment]
Thanks.
I am trying to read the three files:
./Results/totalchem.dat, ./Results/totalspecpos.dat, ./Results/totalspectype.dat 
When I import them on MatLab I only see they all are formed by just one column of numbers (with different rows). I do not think this is correct if I got the code right.
So, I guess I am importing them wrongly, this is the reason I was asking if you could share few more information on how pratically read the data inside these files.

Thank you

**Comment by YujieChi** [comment]
If you don't specify your file reading format in Matlab, it will by default return you a one column data. In this situation, the next step is to reshape your data with the right row and column.
Let 'n' denotes the independent parameters we outputs to the file, then you can reshape your raw reading 'Raw' as
Raw_reshape=reshape(Raw, n, []). Hope it help. 
Thanks.
